server:
  port: 8181
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    dynamic:
      primary: ds0
      strict: true
      datasource:
        ds0:
          url: jdbc:mysql://localhost:3306/eta_cms?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
        ds1:
          url: jdbc:mysql://localhost:3306/theta_sequence?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
      druid:
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: true
        minIdle: 10
        maxActive: 100
        initialSize: 1
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 6000
        poolPreparedStatements: true
        logAbandoned: true
        removeAbandoned: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        filters: stat,wall,log4j2
  redis:
    redisson:
      enable: true
    # 使用开关
    switch: true
    #是否启用缓存
    cache:
      enable: true
      prefix: eta
    #使用驱动 支持 [ jedis | lettuce ] ，缺省为 lettuce
    driver: jedis
    #是否是cluster模式，[true|false] ，缺省为false，即是单节点模式
    multi-nodes: false
    host: localhost
    #password: momo@1234
    port: 6379
    cluster:
      nodes: 12.3.35.31:8001,12.3.35.31:8002,12.3.35.32:8001,12.3.35.32:8002,12.3.35.33:8001,12.3.35.33:8002
      max-redirects: 3
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
    timeout: 3000
mybatis-plus:
  type-handlers-package: com.momo.eta.config