server:
  port: 8181
  tomcat:
    # 当所有可能的请求处理线程都在使用时，传入连接请求会被放进队列中等待，等待队列的最大队列长度。（若超出这个这个数则会CONFUSED_CONNECTION）
    accept-count: 5
    # 服务器在任何给定时间接受和处理的最大连接数。 一旦达到限制，操作系统仍然可以根据“acceptCount”属性接受连接。
    max-connections: 100
    threads:
      #最小线程数（也是Tomcat初始化的连接数）
      min-spare: 20
      #服务器在给定时间能接受的连接数为server.tomcat.max-connections,最大工作线程数（注意！但并不是同时在工作）
      max: 100
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    dynamic:
      primary: ds0
      strict: true
      datasource:
        ds0:
          url: jdbc:mysql://localhost:3306/eta_cms?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
        ds1:
          url: jdbc:mysql://localhost:3306/theta_sequence?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123456
      druid:
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: true
        minIdle: 1
        maxActive: 2
        initialSize: 10
        maxWait: 2000
        timeBetweenEvictionRunsMillis: 6000
        poolPreparedStatements: true
        logAbandoned: true
        removeAbandoned: false
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        filters: stat,wall,log4j2
  redis:
    redisson:
      enable: true
    # 使用开关
    switch: true
    #是否启用缓存
    cache:
      enable: true
      prefix: eta
    #使用驱动 支持 [ jedis | lettuce ] ，缺省为 lettuce
    driver: jedis
    #是否是cluster模式，[true|false] ，缺省为false，即是单节点模式
    multi-nodes: false
    host: localhost
    jedis:
      pool:
        max-active: 100
        max-idle: 50
        min-idle: 10
    timeout: 3000
    connect-timeout: 5000
mybatis-plus:
  type-handlers-package: com.momo.eta.config